INSERT INTO FORMAT (id, name, code, feature, is_active) VALUES
    (FORMAT_SEQ_ID.NEXTVAL, 'REQUEST', 'REQ_PET_CAR', 'PET_CARE', false),
    (FORMAT_SEQ_ID.NEXTVAL, 'REQUEST', 'REQ_BOA_SCH', 'BOARDING_SCHOOL', false),
    (FORMAT_SEQ_ID.NEXTVAL, 'REQUEST', 'REQ_WAL', 'WALK',  false),
    (FORMAT_SEQ_ID.NEXTVAL, 'REQUEST', 'REQ_TRA', 'TRAINING', false),
    (FORMAT_SEQ_ID.NEXTVAL, 'OFFER', 'OFF_PET_CAR', 'PET_CARE', false),
    (FORMAT_SEQ_ID.NEXTVAL, 'OFFER', 'OFF_BOA_SCH', 'BOARDING_SCHOOL', false),
    (FORMAT_SEQ_ID.NEXTVAL, 'OFFER', 'OFF_WAL', 'WALK', false),
    (FORMAT_SEQ_ID.NEXTVAL, 'OFFER', 'OFF_TRA', 'TRAINING', false);
    commit;